services:
  web:
    container_name: php
    build:
      context: app_php
      target: builder
    ports:
      - '8080:80'
      - '8081:81'
  mysql:
    container_name: mysql8
    image: docker.io/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
  phpmyadmin:
      image: docker.io/phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mysql
        PMA_USER: user
        PMA_PASSWORD: pass
        UPLOAD_LIMIT: 20M
      ports:
        - 8082:80

